name: Quality Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          channel: 'stable'

      - name: Install dependencies
        run: |
          flutter pub get
          flutter doctor -v

      - name: Run Flutter Analyze
        run: flutter analyze --no-pub --no-fatal-infos

      - name: Run Widget Tests
        run: flutter test test/widget_test.dart

      - name: Run Unit Tests
        run: flutter test test/main_test.dart 